/* eslint-disable react/jsx-props-no-spreading */

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useFrame, useThree } from "react-three-fiber";
import { useGLTF } from "@react-three/drei/useGLTF";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    "../../../../introModels/original/model-draco.glb"
  );
  return (
    <group
      ref={group}
      {...props}
      dispose={null}
      //   rotation={[-Math.PI / 3, 0, 0]}
    >
      <mesh
        material={materials["White Square"]}
        geometry={nodes.Bishop001.geometry}
        position={[0.02, 0, 0]}
        scale={[13.33, 13.33, 13.33]}
      />
    </group>
  );
}

// useGLTF.preload("../../../../introModels/original/ChessPieceBishop.glb");
