/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: dipietron (https://sketchfab.com/dipietron)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/models/6e1e4cf5c6d74da286cbf425a939c9ce
title: Madrona Invasives
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei/useGLTF";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF(
    "../../../../introModels/Madrona/model-draco.glb"
  );
  return (
    <group ref={group} {...props} dispose={null} scale={[0.2, 0.2, 0.2]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
          <mesh
            material={materials.Wire_4279146624}
            geometry={nodes.Tilt_Brush7143_0.geometry}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
          <mesh
            material={materials.Ink_4279146624}
            geometry={nodes.Tilt_Brush7219_0.geometry}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
          <mesh
            material={materials.ThickPaint_819821}
            geometry={nodes.Tilt_Brush7440_0.geometry}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
          <mesh
            material={materials.Wire_4278271387}
            geometry={nodes.Tilt_Brush7722_0.geometry}
          />
          <mesh
            material={materials.Wire_4278271387}
            geometry={nodes.Tilt_Brush7722_0_1.geometry}
          />
          <mesh
            material={materials.Wire_4278271387}
            geometry={nodes.Tilt_Brush7722_0_2.geometry}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
          <mesh
            material={materials.Wire_4278349609}
            geometry={nodes.Tilt_Brush8145_0.geometry}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
          <mesh
            material={materials.Ink_4287233202}
            geometry={nodes.Tilt_Brush8541_0.geometry}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
          <mesh
            material={materials.Wire_4282157053}
            geometry={nodes.Tilt_Brush8769_0.geometry}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
          <mesh
            material={materials.OilPaint_4282157053}
            geometry={nodes.Tilt_Brush10137_0.geometry}
          />
          <mesh
            material={materials.OilPaint_4282157053}
            geometry={nodes.Tilt_Brush10137_0_1.geometry}
          />
          <mesh
            material={materials.OilPaint_4282157053}
            geometry={nodes.Tilt_Brush10137_0_2.geometry}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
          <mesh
            material={materials.Ink_4282157053}
            geometry={nodes.Tilt_Brush14082_0.geometry}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
          <mesh
            material={materials.OilPaint_4278429502}
            geometry={nodes.Tilt_Brush14553_0.geometry}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
          <mesh
            material={materials.OilPaint_4278806872}
            geometry={nodes.Tilt_Brush16371_0.geometry}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
          <mesh
            material={materials.Ink_4291813886}
            geometry={nodes.Tilt_Brush17437_0.geometry}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
          <mesh
            material={materials.Wire_4293000439}
            geometry={nodes.Tilt_Brush17557_0.geometry}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
          <mesh
            material={materials.Wire_4287806718}
            geometry={nodes.Tilt_Brush17639_0.geometry}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
          <mesh
            material={materials.OilPaint_4287806718}
            geometry={nodes.Tilt_Brush17874_0.geometry}
          />
        </group>
        <group rotation={[Math.PI / 2, 0, 0]} scale={[0.01, 0.01, 0.01]}>
          <mesh
            material={materials.Ink_4287806718}
            geometry={nodes.Tilt_Brush18373_0.geometry}
          />
        </group>
      </group>
    </group>
  );
}

// useGLTF.preload("../../../../introModels/Madrona/model-draco.glb");
