/* eslint-disable react/jsx-props-no-spreading */

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: n- (https://sketchfab.com/n-)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/trefoil-knot-ff3cfe6eb5134f8f98488d5bd6bef6a1
title: Trefoil Knot
*/

import * as THREE from "three";
import React, { useRef, useState, useEffect } from "react";
import { useFrame } from "react-three-fiber";
import { useGLTF } from "@react-three/drei/useGLTF";

import { useAnimations } from "@react-three/drei/useAnimations";

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "../../../../introModels/trefoil_knot/model-draco.gltf"
  );
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[0.93, 0.27, -0.89]} rotation={[1.54, 0, 0]}>
          <group rotation={[Math.PI / 2, 0, 0]}>
            <mesh
              name="Trefoil_KnotShape"
              material={materials.Trefoil_KnotShape}
              geometry={nodes.Trefoil_KnotShape.geometry}
              morphTargetDictionary={
                nodes.Trefoil_KnotShape.morphTargetDictionary
              }
              morphTargetInfluences={
                nodes.Trefoil_KnotShape.morphTargetInfluences
              }
            />
          </group>
        </group>
      </group>
    </group>
  );
}

// useGLTF.preload("../../../../introModels/trefoil_knot/model-draco.gltf");
